name: Easy tester CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Install dependencies
        run: yarn
      - name: Run all tests
        run: yarn test

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: yarn
      - name: Create .nmprc file
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.EASY_TESTER_TOKEN}}" >> .npmrc
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.EASY_TESTER_TOKEN}}
